sudo: required

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - docker

branches:
  only:
    - master

notifications:
  email: false
  slack:
    secure: bXbRfSW/XXXzlFb1bo5R/aDhMOrXMfCimUGdcXrIRLEaTVXO4lPT7iSfyFl9U8NYMkqel8wHoj7xXDGx7PqLqJQjWwLyxMr4+Donhp/HAvEflMWipdOT+FCn/zBaNwD5D3FSMYckOGdf52paFr5rvPrtBCTrLBsA+EtIpzyr9vFzSquai8FsZySr6l2Bf6KHemYmSxOIWdhPBtWW/G835EWcUmKK40TjQ10iYhbRDMu9MC8tJ8+froQxK5TyTWG/bJuvxaDolpxX/v33bmsoiW9eSmEFZVBAchkSxGti8ZTipxgUEaidxwHgCA+yYDy7qkmH7zElikmlONr5+U4t4blgxP01GI9L5YfTAS0EcmyX4UVKimXARYv174lWGVk6lo2dPwh8sJUuMES2UziGbpbyeWyIpy9+KIiWwPDXkLajTlE+P16oTjOHsUNwvneCmCbW+5ObD/8ib9zjpfAfYza9ScYbXQpOfOncH6NRjkv+ro1++tA9B6Q/Tl0Cn0dyo+rtu1lBkj2nu/PTyaSPLjqOybSFg/RXVkAL4bIYjVZLF6alH2AKabLKDvglMGAuLd9MSv1BUeztQLEpFxy057xE6Ue3cm2wWtLzI65ij+pZCE3ojodaOi5BOT4y9VA+jJaD9I4Hl71HE5RZrDfOAzMWp6MmUc5e2HMNFY7QVoc=

before_install:
  - docker build -t builder_image -f docker/Dockerfile.buidler .
  - docker run -it --rm -v $(pwd):/microservice -v $HOME/.m2:/root/.m2 builder_image
  - docker build -t dist_image -f docker/Dockerfile.dist .
  - docker build -t test_image -f docker/Dockerfile.test .

script:
  - docker run -it -v $HOME/.m2:/root/.m2 --name test test_image
  - docker run -d --name dist dist_image
  - docker ps | grep -q dist

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag dist_image patrykks/iosr-zipkin-service;
    docker push patrykks/iosr-zipkin-service;
    fi